### ISSUE TITLE
Stencil: build doesn't work on nx 15.9.x

### ISSUE THREAD

**Issue by marcincichocki** [nxext/nx-extensions#922]
**Describe the bug**
`@nxext/stencil:build` do not work after update to nx 15.9.x. Error message is shown: 
```sh
Cannot find module '@nrwl/workspace/src/utilities/ast-utils'
```

**To Reproduce**
Try to build project with latest nx

**Expected behavior**
Executor should work as before.

**Additional context**
Looks like this file: https://github.com/nxext/nx-extensions/blob/main/packages/stencil/src/utils/ast-utils.ts#L4 is importing file that does not exist anymore. It was moved: https://github.com/nrwl/nx/pull/15540/files#diff-6a3ae3fda9f50d1b43708469ef9af795224222b10b7b4802b561da5529d6db12

**Comment by oscarcornejo** [comment]
I have same problem! :/

**Comment by MrGrigri** [comment]
I get the same thing. Brand new (package-based) NX repo. And the first thing I'm trying to do is add a stencil library and I get this error!

**Comment by naeimsf** [comment]
same issue here

**Comment by erichstark** [comment]
Today I have upgraded nx and I am facing the same issue.

**Comment by MrGrigri** [comment]
@marcincichocki what version were these commands working with?

**Comment by DominikPieper** [comment]
@marcincichocki  Nx changed something internally. The 15.7 nxext package support Nx 15.7. I hadn’t time to update everything that changed

**Comment by dgonzalezr** [comment]
I can confirm the issue and as a workaround, downgrading to Nx 15.7.2 works.

<img width="459" alt="CleanShot 2023-04-23 at 11 25 35@2x" src="https://user-images.githubusercontent.com/328492/233828694-984289d2-8284-415e-9d46-31bfa1265196.png">

Also, to work with the latest `@stencil/core` v3, I need to override the dependency of `@nxext/stencil` in the `packages.json`. Same if you are trying to integrate the latest Storybook v7 in your component library.

**Comment by erichstark** [comment]
@dgonzalezr storybook v7 works only with nrwl 15.9.x no?

**Comment by oscarcornejo** [comment]
Workaround for this problem is to install Stencil directly without using the @nxext/stencil extension and to create components, use the Stencil CLI.

**Comment by luisalfonsosandoval** [comment]
> Workaround for this problem is to install Stencil directly without using the @nxext/stencil extension and to create components, use the Stencil CLI.

 Hi! @oscarcornejo do you happen to have a working example using only the Stencil CLI?

**Comment by matsgottenbos** [comment]
I worked around this by changing one line in @nxext/stencil 15.7.0 using a Yarn patch. I'm using NX 15.9.2. I have been using both without issues since.

I changed line 8 of `@nxext/stencil/src/utils/ast-utils.js` from
```js
const ast_utils_1 = require("@nrwl/workspace/src/utilities/ast-utils");
```
to
```js
const ast_utils_1 = require("@nrwl/workspace/src/utils/ast-utils");
```

**Comment by nirmalathapa** [comment]
Just recently tried nx and I got this issue too. And it took me a while to find out the bug being reported here. Instead of workaround shouldn't there be a good fix? Not a good experience for the first timer using Nx

**Comment by alexco95** [comment]
same issue here

![image](https://github.com/nxext/nx-extensions/assets/90143582/9ff1d829-3b14-4ad1-bc43-8fa26f62ce8b)

looking forward to the patch. Considering using Stencil CLI as @oscarcornejo suggests.

**Comment by erichstark** [comment]
> I worked around this by changing one line in @nxext/stencil 15.7.0 using a Yarn patch. I'm using NX 15.9.2. I have been using both without issues since.
> 
> I changed line 8 of `@nxext/stencil/src/utils/ast-utils.js` from
> 
> ```js
> const ast_utils_1 = require("@nrwl/workspace/src/utilities/ast-utils");
> ```
> 
> to
> 
> ```js
> const ast_utils_1 = require("@nrwl/workspace/src/utils/ast-utils");
> ```

How do you use that patch? It is possible also if I have been using pnpm instead of yarn?

**Comment by matsgottenbos** [comment]
> How do you use that patch? It is possible also if I have been using pnpm instead of yarn?

@erichstark I used `yarn patch`: https://yarnpkg.com/cli/patch
Not familiar with pnpm, but there seems to be something similar: https://pnpm.io/cli/patch
